-- MySQL Script generated by MySQL Workbench
-- Sun Oct 21 00:08:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rocket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rocket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rocket` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `rocket` ;

-- -----------------------------------------------------
-- Table `rocket`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocket`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rocket`.`nucleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocket`.`nucleo` (
  `idnucleo` INT NOT NULL AUTO_INCREMENT,
  `cultura` LONGTEXT NULL,
  `movimento` LONGTEXT NULL,
  `valores` LONGTEXT NULL,
  `facebook` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idnucleo`),
  INDEX `fk_nucleo_login1_idx` (`login_idlogin` ASC) ,
  CONSTRAINT `fk_nucleo_login1`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `rocket`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rocket`.`EJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocket`.`EJ` (
  `idEJ` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cursos` MEDIUMTEXT NOT NULL,
  `numeromembros` VARCHAR(3) NULL,
  `descricao` LONGTEXT NULL,
  `facebook` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `avatar` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `login_idlogin` INT NOT NULL,
  `nucleo_idnucleo` INT NOT NULL,
  PRIMARY KEY (`idEJ`),
  INDEX `fk_EJ_login_idx` (`login_idlogin` ASC) ,
  INDEX `fk_EJ_nucleo1_idx` (`nucleo_idnucleo` ASC) ,
  CONSTRAINT `fk_EJ_login`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `rocket`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EJ_nucleo1`
    FOREIGN KEY (`nucleo_idnucleo`)
    REFERENCES `rocket`.`nucleo` (`idnucleo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rocket`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocket`.`contato` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `nucleo_idnucleo` INT NOT NULL,
  PRIMARY KEY (`idContato`),
  INDEX `fk_contato_nucleo1_idx` (`nucleo_idnucleo` ASC) ,
  CONSTRAINT `fk_contato_nucleo1`
    FOREIGN KEY (`nucleo_idnucleo`)
    REFERENCES `rocket`.`nucleo` (`idnucleo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
